"""
ArmaraOS emitter: generates HAND.toml manifest + pre-compiled AINL IR for ArmaraOS Hands.
"""

from __future__ import annotations
from pathlib import Path
from typing import Any, Dict
import json
import os
from datetime import datetime


def emit_armaraos(ir: Dict[str, Any], source_stem: str, output_dir: Path) -> Dict[str, Path]:
    """
    Emit an ArmaraOS Hand package containing:
    - HAND.toml manifest
    - Compiled AINL IR (JSON)
    - Security policy file
    - Documentation

    Returns dict mapping component names to file paths.
    """
    output_dir = Path(output_dir).expanduser()
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate HAND.toml
    hand_toml = _generate_hand_toml(ir, source_stem)
    hand_toml_path = output_dir / "HAND.toml"
    hand_toml_path.write_text(hand_toml)

    # Write compiled IR (AINL JSON)
    ir_path = output_dir / f"{source_stem}.ainl.json"
    ir_path.write_text(json.dumps(ir, indent=2))

    # Security policy
    security_policy = _generate_security_policy(ir)
    security_path = output_dir / "security.json"
    security_path.write_text(json.dumps(security_policy, indent=2))

    # README
    readme = _generate_readme(ir, source_stem)
    readme_path = output_dir / "README.md"
    readme_path.write_text(readme)

    return {
        "hand_toml": hand_toml_path,
        "ir": ir_path,
        "security": security_path,
        "readme": readme_path,
    }


def _generate_hand_toml(ir: Dict[str, Any], stem: str) -> str:
    """Generate TOML manifest for ArmaraOS Hand."""
    # Extract metadata from IR
    metadata = ir.get("metadata", {})
    author = metadata.get("author", "AINL User")
    description = metadata.get("description", f"AINL-generated hand: {stem}")

    toml_lines = [
        "# ArmaraOS Hand Manifest - Generated by AINL",
        f"# Generated: {datetime.utcnow().isoformat()}Z",
        "",
        "[hand]",
        f'id = "ainl-{stem}"',
        f'name = "{stem.replace("_", " ").title()}"',
        f'version = "1.0.0"',
        f'description = "{description}"',
        f'author = "{author}"',
        "",
        "# Entrypoint is the compiled AINL IR",
        f'entrypoint = "{stem}.ainl.json"',
        "",
        "[config]",
        "max_concurrency = 5",
        "default_timeout = 300",
        "retry_policy = \"exponential_backoff\"",
        "max_retries = 3",
        "",
        "[security]",
        "sandbox = \"wasm\"",
        "max_memory_mb = 256",
        "max_instructions = 10_000_000",
        'allowed_imports = ["env.print", "env.log", "env.sleep", "env.random"]',
        "taint_sources = []  # Filled by AINL security adapter",
        "merkle_audit = true",
        "",
        "[[inputs]]",
        'name = "input"',
        'type = "object"',
        'description = "Input data for the hand"',
        "",
        "[[outputs]]",
        'name = "result"',
        'type = "object"',
        'description = "Hand execution result"',
        "",
        "[[outputs]]",
        'name = "metrics"',
        'type = "object"',
        'description = "Execution metrics (tokens, duration, cost)"',
        "",
        "[resources]",
        "cpu_millicores = 500",
        "memory_mb = 256",
        "ephemeral_storage_mb = 100",
        "",
        "[metadata]",
        f'tags = ["ainl", "{stem}"]',
        'icon = "🧠"',
        'color = "#6366f1"',
        "",
    ]
    return "\n".join(toml_lines)


def _generate_security_policy(ir: Dict[str, Any]) -> Dict[str, Any]:
    """Generate ArmaraOS-compatible security policy."""
    security = ir.get("_security", {})
    return {
        "version": "1.0",
        "sandbox": security.get("sandbox", "wasm"),
        "wasm_config": security.get("wasm_config", {
            "max_memory_mb": 256,
            "max_instructions": 10_000_000,
            "allowed_imports": ["env.print", "env.log", "env.sleep", "env.random"],
            "blocked_syscalls": ["filesystem", "network", "process"],
            "fuel_limit": None,
        }),
        "taint": security.get("taint", {"sources": [], "tracking_enabled": True}),
        "merkle": security.get("merkle", {"hooks_enabled": True, "incremental": True}),
        "allowed_networks": [],  # Can be populated by user
        "max_execution_time_sec": 300,
    }


def _generate_readme(ir: Dict[str, Any], stem: str) -> str:
    """Generate README for the hand package."""
    return f"""# AINL ArmaraOS Hand: {stem}

This hand was automatically generated by AINL (AI Native Language).

## Files

- `HAND.toml` - ArmaraOS hand manifest
- `{stem}.ainl.json` - Compiled AINL IR
- `security.json` - Security policy (WASM sandbox, taint tracking)
- `README.md` - This file

## Usage

1. Ensure AINL is installed and integrated with ArmaraOS:
   ```bash
   ainl install armaraos
   ```

2. Copy this directory to your ArmaraOS hands directory (or reference it directly).

3. Run the hand via ArmaraOS CLI:
   ```bash
   armaraos hand run ainl-{stem} --input '{{}}'
   ```

## AINL Source

Original AINL source is required for modifications. Recompile with:
   ```bash
   ainl emit --target armaraos -o . source.ainl
   ```

## Security

This hand runs in a WASM sandbox with:
- Memory limit: 256 MB
- Instruction limit: 10M
- Taint tracking enabled
- Merkle audit trail

See `security.json` for full policy.
"""
