"""Refresh the auto-generated tier badge block on every `docs/adapters/*.md` page.

Each adapter doc carries a machine-fenced badge block that is sourced from
**`ADAPTER_REGISTRY.json`** (`tier`, `description`, `targets`, `privilege_tier`,
…). This script regenerates the block in place — text outside the fence is
never touched. The block looks like:

    <!-- adapter-badge:begin auto-generated by scripts/refresh_adapter_doc_badges.py; edit ADAPTER_REGISTRY.json -->
    > **Tier:** 🟢 **Core** · **Group:** `postgres` · **Verbs:** `query`, `execute`, `transaction` · **Privilege:** `network` · **Sandbox-safe:** no
    >
    > Production-grade adapter on the gold path. Tier model and full adapter catalog: [`ADAPTER_TIERS.md`](ADAPTER_TIERS.md).
    <!-- adapter-badge:end -->

Usage:

    python3 scripts/refresh_adapter_doc_badges.py             # rewrite in place
    python3 scripts/refresh_adapter_doc_badges.py --check     # exit 1 if any doc is out of sync
    python3 scripts/refresh_adapter_doc_badges.py --dry-run   # print diffs only

Design contract:

* **Idempotent.** A second run with the same registry state produces a
  byte-identical file. CI runs `--check` and fails if anyone hand-edited a
  doc to disagree with the registry, or forgot to refresh after editing
  the registry.
* **Fence-only edits.** Only the text between the `<!-- adapter-badge:begin -->`
  and `<!-- adapter-badge:end -->` HTML comments is rewritten. Everything
  else is left exactly as the human/agent author wrote it.
* **Honest about missing docs.** Extended-tier adapters that don't yet have
  a doc page in `docs/adapters/` are listed under `missing_docs` in the
  `--check` output (informational; does **not** cause the check to fail).
* **No silent drift.** Filename → registry-key mapping is explicit
  (`DOC_FILENAME_TO_REGISTRY_KEY`); doc files that aren't adapter pages
  (`README.md`, `ADAPTER_TIERS.md`, `CONTRACT_AND_COMPILER.md`,
  `OPENCLAW_ADAPTERS.md`) are listed under `SKIP_FILES` and are not
  touched.

Part of `LONG_TERM_FIXES_TRACKER` **T3.2**.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = REPO_ROOT / "ADAPTER_REGISTRY.json"
ADAPTER_DOCS_DIR = REPO_ROOT / "docs" / "adapters"

# Filenames in docs/adapters/ that are NOT adapter-page docs.
SKIP_FILES = {
    "README.md",
    "ADAPTER_TIERS.md",
    "CONTRACT_AND_COMPILER.md",
    "OPENCLAW_ADAPTERS.md",
}

# Explicit mapping for the cases where docs/adapters/<NAME>.md does not map to
# ADAPTER_REGISTRY.adapters[<name>.lower()].  Any filename not listed here is
# resolved by lowercasing the stem.
DOC_FILENAME_TO_REGISTRY_KEY: Dict[str, str] = {
    "MEMORY_CONTRACT.md": "memory",
    "MEMORY_CONTRACT_V1_1_RFC.md": "memory",
}

# Tier visuals.
TIER_EMOJI = {"core": "🟢", "extended": "🟡"}
TIER_LABEL = {"core": "Core", "extended": "Extended"}

# How many verbs to inline before truncating.
VERB_INLINE_LIMIT = 4

FENCE_BEGIN_RE = re.compile(
    r"<!--\s*adapter-badge:begin[^>]*-->",
    re.IGNORECASE,
)
FENCE_END_RE = re.compile(r"<!--\s*adapter-badge:end\s*-->", re.IGNORECASE)
FULL_FENCE_RE = re.compile(
    r"<!--\s*adapter-badge:begin[^>]*-->.*?<!--\s*adapter-badge:end\s*-->",
    re.IGNORECASE | re.DOTALL,
)

FRONTMATTER_RE = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)
FIRST_HEADING_RE = re.compile(r"^(#{1,2})\s+.*$", re.MULTILINE)


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _format_verbs(targets: Dict[str, object]) -> str:
    verbs = list(targets.keys())
    if not verbs:
        return "_no verbs declared_"
    head = ", ".join(f"`{v}`" for v in verbs[:VERB_INLINE_LIMIT])
    if len(verbs) > VERB_INLINE_LIMIT:
        return f"{head}, … ({len(verbs)} total)"
    return head


def _format_bool(b: object) -> str:
    if b is True:
        return "yes"
    if b is False:
        return "no"
    return "—"


def render_badge_block(
    *,
    adapter_key: str,
    entry: Dict[str, object],
    tier_meanings: Dict[str, str],
) -> str:
    tier = str(entry.get("tier", "")).lower() or "core"
    emoji = TIER_EMOJI.get(tier, "•")
    label = TIER_LABEL.get(tier, tier.title())
    verbs_str = _format_verbs(entry.get("targets", {}) or {})
    privilege = entry.get("privilege_tier")
    sandbox_safe = entry.get("sandbox_safe")
    network_facing = entry.get("network_facing")

    privilege_str = f"`{privilege}`" if privilege else "—"

    facts: List[str] = [
        f"**Tier:** {emoji} **{label}**",
        f"**Group:** `{adapter_key}`",
        f"**Verbs:** {verbs_str}",
        f"**Privilege:** {privilege_str}",
        f"**Sandbox-safe:** {_format_bool(sandbox_safe)}",
    ]
    if network_facing is True:
        facts.append("**Network-facing:** yes")

    fact_line = " · ".join(facts)
    meaning = tier_meanings.get(tier, "").strip()
    # Truncate the tier-meaning to the first sentence to keep the badge compact.
    if meaning:
        first_sentence = meaning.split(". ", 1)[0].rstrip(".") + "."
    else:
        first_sentence = "See `docs/adapters/ADAPTER_TIERS.md` for the tier definition."

    lines = [
        "<!-- adapter-badge:begin auto-generated by scripts/refresh_adapter_doc_badges.py; edit ADAPTER_REGISTRY.json -->",
        f"> {fact_line}",
        ">",
        f"> {first_sentence} Tier model and full adapter catalog: [`ADAPTER_TIERS.md`](ADAPTER_TIERS.md).",
        "<!-- adapter-badge:end -->",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Doc rewriting
# ---------------------------------------------------------------------------


def _find_insertion_point(text: str) -> Optional[int]:
    """Return character index at which to splice the badge block.

    The badge sits immediately after the first H1/H2 heading (skipping any
    YAML frontmatter). Returns None if no heading is found.
    """
    cursor = 0
    fm = FRONTMATTER_RE.match(text)
    if fm:
        cursor = fm.end()
    match = FIRST_HEADING_RE.search(text, cursor)
    if not match:
        return None
    # splice after the newline that ends the heading line
    return match.end()


def apply_badge(text: str, badge_block: str) -> str:
    """Return `text` with `badge_block` either replacing an existing fenced
    block or inserted after the first heading.

    Always normalizes to exactly one blank line before and after the block.
    """
    if FULL_FENCE_RE.search(text):
        # In-place replacement preserves surrounding whitespace.
        return FULL_FENCE_RE.sub(badge_block, text)

    insertion = _find_insertion_point(text)
    if insertion is None:
        raise ValueError("could not find an H1/H2 heading to anchor the badge")

    before = text[:insertion]
    after = text[insertion:]
    # Ensure one blank line between heading and badge, and one blank line
    # between badge and the next paragraph.
    after = after.lstrip("\n")
    return before + "\n" + badge_block + "\n\n" + after


# ---------------------------------------------------------------------------
# File walker
# ---------------------------------------------------------------------------


def resolve_registry_key(filename: str) -> Optional[str]:
    if filename in DOC_FILENAME_TO_REGISTRY_KEY:
        return DOC_FILENAME_TO_REGISTRY_KEY[filename]
    return filename[:-3].lower() if filename.endswith(".md") else None


def collect_doc_targets() -> Tuple[List[Path], List[str]]:
    """Return (paths_to_stamp, skipped_filenames)."""
    if not ADAPTER_DOCS_DIR.is_dir():
        raise FileNotFoundError(f"missing adapter docs dir: {ADAPTER_DOCS_DIR}")
    targets: List[Path] = []
    skipped: List[str] = []
    for p in sorted(ADAPTER_DOCS_DIR.glob("*.md")):
        if p.name in SKIP_FILES:
            skipped.append(p.name)
            continue
        targets.append(p)
    return targets, skipped


def missing_extended_docs(adapters: Dict[str, Dict[str, object]], stamped_keys: set) -> List[str]:
    """List extended adapters that don't have a dedicated doc page yet."""
    out: List[str] = []
    for key, entry in adapters.items():
        if not isinstance(entry, dict):
            continue
        if entry.get("tier") != "extended":
            continue
        if key not in stamped_keys:
            out.append(key)
    return sorted(out)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def process(
    *,
    check: bool = False,
    dry_run: bool = False,
) -> int:
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    adapters: Dict[str, Dict[str, object]] = registry.get("adapters", {}) or {}
    tier_meanings: Dict[str, str] = registry.get("tier_meanings", {}) or {}

    doc_paths, skipped = collect_doc_targets()
    stamped_keys: set = set()
    changes: List[Tuple[Path, str, str]] = []  # (path, old, new)
    unmapped: List[str] = []

    for path in doc_paths:
        key = resolve_registry_key(path.name)
        if not key or key not in adapters:
            unmapped.append(path.name)
            continue
        stamped_keys.add(key)
        entry = adapters[key]
        badge = render_badge_block(
            adapter_key=key, entry=entry, tier_meanings=tier_meanings
        )
        old_text = path.read_text(encoding="utf-8")
        new_text = apply_badge(old_text, badge)
        if new_text != old_text:
            changes.append((path, old_text, new_text))

    missing_extended = missing_extended_docs(adapters, stamped_keys)

    # ---- output mode handling ----
    if dry_run or check:
        for path, old, new in changes:
            diff = difflib.unified_diff(
                old.splitlines(keepends=True),
                new.splitlines(keepends=True),
                fromfile=str(path.relative_to(REPO_ROOT)),
                tofile=str(path.relative_to(REPO_ROOT)),
                n=2,
            )
            sys.stdout.write("".join(diff))
        print()
        print(f"summary: {len(changes)} doc(s) would change; "
              f"{len(doc_paths) - len(changes)} already in sync; "
              f"{len(skipped)} skipped ({', '.join(skipped) or '-'}); "
              f"{len(unmapped)} unmapped ({', '.join(unmapped) or '-'})")
        if missing_extended:
            print(f"missing extended docs (informational, not a failure): "
                  f"{', '.join(missing_extended)}")
        if check and changes:
            print("ERROR: adapter doc badges are out of sync. "
                  "Run `python3 scripts/refresh_adapter_doc_badges.py` and commit.")
            return 1
        return 0

    # ---- write mode ----
    for path, _old, new in changes:
        path.write_text(new, encoding="utf-8")
    print(f"updated {len(changes)} adapter doc(s); "
          f"{len(doc_paths) - len(changes)} already in sync; "
          f"skipped {len(skipped)}; unmapped {len(unmapped)}")
    if unmapped:
        print(f"  unmapped (no registry entry): {', '.join(unmapped)}")
    if missing_extended:
        print(f"  extended adapters without a doc page (informational): "
              f"{', '.join(missing_extended)}")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--check", action="store_true",
                   help="exit 1 if any doc is out of sync; do not write")
    p.add_argument("--dry-run", action="store_true",
                   help="print diff of pending changes; do not write")
    args = p.parse_args()
    if args.check and args.dry_run:
        p.error("--check and --dry-run are mutually exclusive")
    return process(check=args.check, dry_run=args.dry_run)


if __name__ == "__main__":
    sys.exit(main())
