"""
Emit a llama.cpp-compatible GBNF grammar for strict-valid AINL.

Consumes OP_REGISTRY and ADAPTER_EFFECT from the compiler/effect-analysis to
produce a self-contained GBNF string that constrains LLM decoding to only
emit syntactically valid AINL programs (compact or opcode style).

Usage (standalone):
    python -m tooling.grammar_emit_gbnf            # prints GBNF to stdout
    python -m tooling.grammar_emit_gbnf -o out.gbnf # writes to file

Usage (library):
    from tooling.grammar_emit_gbnf import emit_gbnf
    gbnf_str = emit_gbnf()
"""
from __future__ import annotations

import argparse
import sys
from typing import Dict, List, Optional, Set

from compiler_v2 import MODULE_ALIASES, OP_REGISTRY
from tooling.effect_analysis import ADAPTER_EFFECT

_TOP_OPS = sorted(
    op for op, spec in OP_REGISTRY.items()
    if op != "L:" and spec.get("scope") in ("top", "any")
)
_LABEL_OPS = sorted(
    op for op, spec in OP_REGISTRY.items()
    if op != "L:" and spec.get("scope") in ("label", "any")
)

_ADAPTER_VERBS: Dict[str, Set[str]] = {}
for dotted in ADAPTER_EFFECT:
    parts = dotted.split(".", 1)
    if len(parts) == 2:
        _ADAPTER_VERBS.setdefault(parts[0], set()).add(parts[1])


def _esc(s: str) -> str:
    return s.replace('"', r'\"')


def _alt(items: List[str]) -> str:
    if len(items) == 1:
        return f'"{_esc(items[0])}"'
    return " | ".join(f'"{_esc(i)}"' for i in sorted(items))


def emit_gbnf(*, include_compact: bool = True) -> str:
    """Return a GBNF grammar string for strict-valid AINL."""
    lines: List[str] = []
    lines.append("# AINL strict-valid grammar (auto-generated by tooling/grammar_emit_gbnf.py)")
    lines.append("")

    lines.append('root ::= program')
    lines.append("")

    lines.append('program ::= (comment | blank-line | top-level-line | label-block | compact-block)+ ')
    lines.append("")

    lines.append('ws ::= " "+')
    lines.append('opt-ws ::= " "*')
    lines.append('nl ::= "\\n"')
    lines.append('blank-line ::= opt-ws nl')
    lines.append('comment ::= opt-ws "#" [^\\n]* nl')
    lines.append("")

    lines.append("# --- identifiers and literals ---")
    lines.append('ident ::= [a-zA-Z_] [a-zA-Z0-9_]*')
    lines.append('dotted-ident ::= ident "." ident')
    lines.append('number ::= "-"? [0-9]+ ("." [0-9]+)?')
    lines.append('dq-string ::= "\\"" [^"\\n]* "\\""')
    lines.append('sq-string ::= "\'" [^\'\\n]* "\'"')
    lines.append('string-lit ::= dq-string | sq-string')
    lines.append('var-or-lit ::= ident | dotted-ident | number | string-lit')
    lines.append('expr ::= var-or-lit (ws var-or-lit)*')
    lines.append('arrow-var ::= "->" ident')
    lines.append("")

    lines.append("# --- label declarations (opcode style) ---")
    lines.append('label-header ::= "L" [0-9]+ "_"? [a-zA-Z0-9_]* ":" opt-ws nl')
    lines.append('label-block ::= label-header (label-line)+')
    lines.append('label-line ::= ws label-op nl')
    lines.append("")

    top_ops_str = _alt(_TOP_OPS)
    lines.append(f"# top-level opcodes")
    lines.append(f'top-op-name ::= {top_ops_str}')
    lines.append('top-level-line ::= top-op-name ws expr opt-ws nl')
    lines.append("")

    lines.append("# --- label-level opcodes ---")
    lines.append('r-line ::= "R" ws adapter-call (ws arrow-var)? ')
    lines.append('j-line ::= "J" ws expr')
    lines.append('set-line ::= "Set" ws ident ws expr')
    lines.append('x-line ::= "X" ws ident ws expr')
    lines.append('if-line ::= "If" ws "(" expr ")" ws arrow-var ws arrow-var')
    lines.append('while-line ::= "While" ws "(" expr ")" ws arrow-var')
    lines.append('call-line ::= "Call" ws ident')
    lines.append('err-line ::= "Err" ws expr')
    lines.append('retry-line ::= "Retry" (ws expr)?')
    lines.append('memory-op ::= ("memory." | "persona.") ident (ws expr)?')
    lines.append("")
    lines.append('label-op ::= r-line | j-line | set-line | x-line | if-line | while-line | call-line | err-line | retry-line | memory-op')
    lines.append("")

    adapters = sorted(_ADAPTER_VERBS.keys())
    adapter_alts = _alt(adapters) if adapters else '"core"'
    lines.append(f'adapter-name ::= {adapter_alts}')
    lines.append('adapter-verb ::= [A-Z] [A-Z0-9_]*')
    lines.append('adapter-call ::= adapter-name "." adapter-verb (ws expr)?')
    lines.append("")

    if include_compact:
        lines.append("# --- compact syntax ---")
        lines.append('compact-header ::= ident ("@cron" ws string-lit)? ("@api" ws string-lit)? ":" opt-ws nl')
        lines.append('compact-block ::= compact-header (compact-line)+')
        lines.append('compact-line ::= ws compact-stmt nl')
        lines.append('compact-assign ::= ident ws "=" ws (dotted-ident | ident) (ws expr)?')
        lines.append('compact-bare-call ::= dotted-ident (ws expr)?')
        lines.append('compact-in ::= "in:" (ws ident)+')
        lines.append('compact-out ::= "out" ws expr')
        lines.append('compact-err ::= "err" ws expr')
        lines.append('compact-call ::= "call" ws ident')
        lines.append('compact-if ::= "if" ws expr ":" ')
        lines.append('compact-config ::= "config" ws ident ":" ident')
        lines.append('compact-state ::= "state" ws ident ":" ident')
        lines.append('compact-stmt ::= compact-assign | compact-bare-call | compact-in | compact-out | compact-err | compact-call | compact-if | compact-config | compact-state | comment')
        lines.append("")

    lines.append("# --- frame hints (comment-based, optional) ---")
    lines.append('frame-hint ::= "# frame:" ws ident (":" ws ident)?')
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Emit GBNF grammar for strict-valid AINL")
    parser.add_argument("-o", "--output", help="Write to file instead of stdout")
    parser.add_argument("--no-compact", action="store_true", help="Omit compact syntax rules")
    args = parser.parse_args()

    gbnf = emit_gbnf(include_compact=not args.no_compact)
    if args.output:
        with open(args.output, "w") as f:
            f.write(gbnf)
        print(f"Wrote {len(gbnf)} bytes to {args.output}", file=sys.stderr)
    else:
        print(gbnf)


if __name__ == "__main__":
    main()
