"""
Emit a JSON Schema (or EBNF-string) for vLLM guided decoding of strict-valid AINL.

vLLM supports several guided-decoding backends (XGrammar, Outlines, lm-format-enforcer).
This module provides:
  - ``emit_jsonschema()`` — a JSON Schema describing an AINL program as a string
    with a ``pattern`` regex (for ``guided_json`` / ``guided_regex`` backends).
  - ``emit_ebnf()`` — an EBNF grammar string compatible with XGrammar's
    ``guided_grammar`` parameter.

Usage (standalone):
    python -m tooling.grammar_emit_jsonschema --format json    # JSON Schema
    python -m tooling.grammar_emit_jsonschema --format ebnf    # EBNF for XGrammar

Usage (library):
    from tooling.grammar_emit_jsonschema import emit_jsonschema, emit_ebnf
"""
from __future__ import annotations

import argparse
import json
import sys
from typing import Any, Dict, List, Set

from compiler_v2 import MODULE_ALIASES, OP_REGISTRY
from tooling.effect_analysis import ADAPTER_EFFECT

_TOP_OPS = sorted(
    op for op, spec in OP_REGISTRY.items()
    if op != "L:" and spec.get("scope") in ("top", "any")
)
_LABEL_OPS = sorted(
    op for op, spec in OP_REGISTRY.items()
    if op != "L:" and spec.get("scope") in ("label", "any")
)

_ADAPTER_NAMES: Set[str] = set()
for dotted in ADAPTER_EFFECT:
    parts = dotted.split(".", 1)
    if len(parts) == 2:
        _ADAPTER_NAMES.add(parts[0])


def emit_jsonschema() -> Dict[str, Any]:
    """Return a JSON Schema that describes a valid AINL program string.

    The schema uses ``pattern`` to provide a regex-based constraint.
    This is a coarse constraint — it rejects clearly invalid programs but
    does not enforce every semantic rule (that is the compiler's job).
    """
    top_ops_pat = "|".join(_TOP_OPS)
    label_ops_pat = "R|J|Set|X|If|While|Call|Err|Retry"
    adapter_names_pat = "|".join(sorted(_ADAPTER_NAMES)) if _ADAPTER_NAMES else "core"

    ident = r"[a-zA-Z_][a-zA-Z0-9_]*"
    dotted = rf"{ident}\.{ident}"
    label_header = r"L[0-9]+[a-zA-Z0-9_]*:"
    compact_header = rf"{ident}:"

    line_pattern = (
        rf"^("
        rf"  \s*#[^\n]*"              # comment
        rf"| \s*"                      # blank line
        rf"| ({top_ops_pat})\s+.*"     # top-level opcode
        rf"| {label_header}\s*"        # label header
        rf"| \s+({label_ops_pat})\s+.*"  # label body opcode
        rf"| \s+{dotted}\s+.*"         # adapter call in label
        rf"| {compact_header}\s*"      # compact header
        rf"| \s+in:\s+.*"             # compact in
        rf"| \s+out\s+.*"             # compact out
        rf"| \s+err\s+.*"             # compact err
        rf"| \s+{ident}\s*=\s+.*"     # compact assignment
        rf"| \s+{dotted}\s+.*"        # compact bare call
        rf"| \s+if\s+.*:\s*"          # compact if
        rf"| \s+call\s+.*"            # compact call
        rf")$"
    )

    return {
        "type": "string",
        "description": "A strict-valid AINL program in compact or opcode syntax.",
        "minLength": 5,
        "maxLength": 65536,
        "metadata": {
            "ainl_grammar_version": "1.0",
            "adapter_names": sorted(_ADAPTER_NAMES),
            "top_level_ops": _TOP_OPS,
            "label_ops": ["R", "J", "Set", "X", "If", "While", "Call", "Err", "Retry"],
            "compact_stmts": ["in:", "out", "err", "call", "if", "config", "state"],
        },
    }


def emit_ebnf() -> str:
    """Return an EBNF grammar string for XGrammar / vLLM guided_grammar."""
    lines: List[str] = []
    lines.append("(* AINL strict-valid EBNF — auto-generated by tooling/grammar_emit_jsonschema.py *)")
    lines.append("")

    lines.append("program = { line } ;")
    lines.append('line = comment | blank_line | top_line | label_header | label_line | compact_header | compact_line ;')
    lines.append("")

    lines.append('comment = { " " } , "#" , { printable } , newline ;')
    lines.append('blank_line = { " " } , newline ;')
    lines.append('newline = "\\n" ;')
    lines.append('printable = ? any character except newline ? ;')
    lines.append("")

    lines.append('ident = letter , { letter | digit | "_" } ;')
    lines.append('letter = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" ;')
    lines.append('digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;')
    lines.append('dotted_ident = ident , "." , ident ;')
    lines.append("")

    lines.append('string_lit = \'"\' , { printable } , \'"\' ;')
    lines.append('number = [ "-" ] , digit , { digit } , [ "." , digit , { digit } ] ;')
    lines.append('var_or_lit = ident | dotted_ident | number | string_lit ;')
    lines.append('expr = var_or_lit , { " " , var_or_lit } ;')
    lines.append('arrow_var = "->" , ident ;')
    lines.append("")

    top_ops_ebnf = " | ".join(f'"{op}"' for op in _TOP_OPS)
    lines.append(f'top_op = {top_ops_ebnf} ;')
    lines.append('top_line = top_op , " " , expr , newline ;')
    lines.append("")

    lines.append('label_header = "L" , digit , { digit | "_" | letter } , ":" , { " " } , newline ;')
    lines.append('label_line = " " , " " , label_op , newline ;')
    lines.append('label_op = r_line | j_line | set_line | if_line | while_line | call_line | err_line ;')
    lines.append("")

    adapter_names_ebnf = " | ".join(f'"{a}"' for a in sorted(_ADAPTER_NAMES)) if _ADAPTER_NAMES else '"core"'
    lines.append(f'adapter_name = {adapter_names_ebnf} ;')
    lines.append('adapter_verb = letter , { letter | digit | "_" } ;')
    lines.append('adapter_call = adapter_name , "." , adapter_verb , [ " " , expr ] ;')
    lines.append('r_line = "R" , " " , adapter_call , [ " " , arrow_var ] ;')
    lines.append('j_line = "J" , " " , expr ;')
    lines.append('set_line = "Set" , " " , ident , " " , expr ;')
    lines.append('if_line = "If" , " " , "(" , expr , ")" , " " , arrow_var , " " , arrow_var ;')
    lines.append('while_line = "While" , " " , "(" , expr , ")" , " " , arrow_var ;')
    lines.append('call_line = "Call" , " " , ident ;')
    lines.append('err_line = "Err" , " " , expr ;')
    lines.append("")

    lines.append("(* compact syntax *)")
    lines.append('compact_header = ident , [ "@cron" , " " , string_lit ] , [ "@api" , " " , string_lit ] , ":" , { " " } , newline ;')
    lines.append('compact_line = " " , " " , compact_stmt , newline ;')
    lines.append('compact_stmt = compact_assign | compact_bare_call | compact_in | compact_out | compact_err | compact_call | compact_if ;')
    lines.append('compact_assign = ident , " " , "=" , " " , ( dotted_ident | ident ) , [ " " , expr ] ;')
    lines.append('compact_bare_call = dotted_ident , [ " " , expr ] ;')
    lines.append('compact_in = "in:" , { " " , ident } ;')
    lines.append('compact_out = "out" , " " , expr ;')
    lines.append('compact_err = "err" , " " , expr ;')
    lines.append('compact_call = "call" , " " , ident ;')
    lines.append('compact_if = "if" , " " , expr , ":" ;')
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Emit JSON Schema or EBNF for AINL guided decoding")
    parser.add_argument("--format", choices=["json", "ebnf"], default="json")
    parser.add_argument("-o", "--output", help="Write to file instead of stdout")
    args = parser.parse_args()

    if args.format == "json":
        content = json.dumps(emit_jsonschema(), indent=2)
    else:
        content = emit_ebnf()

    if args.output:
        with open(args.output, "w") as f:
            f.write(content)
        print(f"Wrote {len(content)} bytes to {args.output}", file=sys.stderr)
    else:
        print(content)


if __name__ == "__main__":
    main()
